apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: lab14
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goves
  template:
    metadata:
      labels:
        app: goves
    spec:
      containers:
      - name: governoes
        image: augustocbn/governoes:3.0
      tolerations:
      - effect: NoSchedule
        key: dedicated
        value: test-team
